implement firebase auth via rest
paysera/kotlin-lib-firebase-rest-auth pull request #2
Opened 2020-09-14 15:43 UTC by gilbertparreno

2020-09-14 16:11 UTC, edgar-zigis requested changes

2020-09-14 16:11 UTC, edgar-zigis commented on app/.gitignore
> +/build
I think that this .gitignore can be used as it will remove idea and other unnecessary files:
https://github.com/paysera/kotlin-lib-accounts-sdk/blob/master/.gitignore

2020-09-14 16:11 UTC, edgar-zigis commented on app/src/main/java/com/paysera/lib/firebaserestauth/utils/IdTokenParser.kt
> +        if (TextUtils.isEmpty(rawUserInfo)) {
`if (rawUserInfo.isNullOrEmpty())`

2020-09-14 16:11 UTC, edgar-zigis commented on app/build.gradle
> +    implementation "androidx.core:core-ktx:$core_ktx_version"
is `ktx` core needed? is it because of the **Keep** annotation? we could writeup the proguard file here and just keep that class in order not to remove it during the minification process.

2020-09-14 16:11 UTC, edgar-zigis commented on app/build.gradle
> +apply plugin: 'com.android.library'
is it necessary to have this library as `android-library`? does Firebase requires that? because I see that you only use 2 methods from Android (TextUtils and Handler) which can be easily replaced by some kotlin native code.

2020-09-14 16:12 UTC, edgar-zigis commented on app/build.gradle
> +    implementation "androidx.core:core-ktx:$core_ktx_version"
this comment is related with whether we need to keep this as android library, if yes - ignore the comment and let's have ktx-core here.

2020-09-15 02:27 UTC, gilbertparreno commented on app/.gitignore
> +/build
I didn't notice this, this should be removed because I already have one on the root directory.

2020-09-15 03:18 UTC, gilbertparreno commented on app/build.gradle
> +apply plugin: 'com.android.library'
Firebase also using this `com.google.android.gms.tasks`

2020-09-15 04:50 UTC, gilbertparreno commented on app/build.gradle
> +    implementation "androidx.core:core-ktx:$core_ktx_version"
May we could just include `RestAuthRegistrar` on our proguard.

2020-09-15 05:05 UTC, gilbertparreno commented on app/src/main/java/com/paysera/lib/firebaserestauth/utils/IdTokenParser.kt
> +        if (TextUtils.isEmpty(rawUserInfo)) {
fixed

2020-09-15 05:05 UTC, gilbertparreno commented on app/build.gradle
> +    implementation "androidx.core:core-ktx:$core_ktx_version"
fixed

2020-09-15 06:26 UTC, edgar-zigis approved these changes

2020-09-15 06:26 UTC, merged